### ISSUE TITLE
thumborize not working - bad gateway

### ISSUE THREAD

**Issue by nickdietel** [thumbor/thumbor#924] opened 2017-05-13 08:31 UTC
### Thumbor request URL
http://thumborize.me/?url=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2016%2F03%2F28%2F12%2F35%2Fcat-1285634_960_720.png

### Expected behaviour
n/a

### Actual behaviour
502 Bad Gateway

### Operating system
n/a

### Your thumbor.conf
n/a

**Comment by masom** [comment] 2017-05-15 12:52
This is a duplicate of https://github.com/thumbor/thumbor/issues/900

**Closed by masom** 2017-05-15 12:52 UTC
