### ISSUE TITLE
Change the /unsafe name, based on configuration variable?

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor#980] opened 2017-09-12 20:11 UTC
The unsafe URL has this format:
https://domain.com/unsafe/site.com/image.jpg

I would prefer to use a configuration variable and define a different term, instead of "unsafe", for example:
https://domain.com/alpha/site.com/image.jpg

What approach do you recommend me to use? I don't think is better to do an Nginx rewrite, when we can configure this at application level, is more efficient, IMO?

**Comment by heynemann** [comment] 2017-11-16 01:01
Unsafe is there as a powerful reminder that you should not, under any circumstance, use it in production. It will be VERY easy for someone to DDoS your thumbor server.

We are very committed to ensuring thumbor is safe by design. Allowing people to change this would not move us in that direction.

If you have any further questions on this issue, please reopen it.

**Closed by heynemann** 2017-11-16 01:01 UTC

**Comment by MrCoding** [comment] 2019-12-19 18:57
I fully understand why not to use the 'unsafe' part in a production environment. But to be sure DDoS attacks are not interfere my public Thumbor services I tested it very carefully and - for now - it looks like DDoS attacks are almost impossible to harm my services. (Never got any issues. Not yet!)

If you like to use this public (free and fully featured) service you are welcome at :

Link : https://Thumbor.Rocks/unsafe/ [etc]
Example : https://thumbor.rocks/unsafe/400x0/http://media.mycdn.rocks/Media_Photos/TheChive/r9vc0f2z.jpg
