### ISSUE TITLE
Preserving the original HTTP request headers

### ISSUE THREAD

**Issue by khelll** [thumbor/thumbor#792] opened 2016-08-02 11:53 UTC
### Thumbor request URL

 [This is a public link] curl -I http://thumborhost/unsafe/80x80/filters:extract_cover():format(png)/http://hsoub-accounts-staging.s3.amazonaws.com/uploads/avatar/default
### Expected behaviour

I need the s3 headers to get back as is, at least the non-caching related ones. And if I set MAX_AGE=False it should return the original caching headers.
### Actual behaviour

Original headers are not returned

**Comment by heynemann** [comment] 2017-11-16 01:56
Yes, thumbor strips away all metadata in an image. That's by design as our focus is to reduce the response size. Sorry for the very long time it took me to reply.

I'm closing this.

If you have any further questions on this issue, please reopen it.

**Closed by heynemann** 2017-11-16 01:56 UTC
