### ISSUE TITLE
exceptions not logged to custom error handler

### ISSUE THREAD

**Issue by phoet** [thumbor/thumbor#537] opened 2015-08-18 09:12 UTC
we want to use sentry for custom error reporting, but it does not receive any errors, eventhough we see some in the logs:

```
2015-08-18T08:58:34.870570+00:00 app[web.6]: 2015-08-18 08:58:34 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
2015-08-18T08:58:34.870576+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
2015-08-18T08:58:34.870578+00:00 app[web.6]:     yielded = self.gen.throw(*exc_info)
2015-08-18T08:58:34.870579+00:00 app[web.6]:   File "/app/.heroku/src/thumbor/thumbor/handlers/__init__.py", line 86, in get_image
2015-08-18T08:58:34.870580+00:00 app[web.6]:     self.context.request.image_url
2015-08-18T08:58:34.870582+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
2015-08-18T08:58:34.870583+00:00 app[web.6]:     value = future.result()
2015-08-18T08:58:34.870585+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
2015-08-18T08:58:34.870586+00:00 app[web.6]:     raise_exc_info(self._exc_info)
2015-08-18T08:58:34.870588+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
2015-08-18T08:58:34.870589+00:00 app[web.6]:     yielded = self.gen.send(value)
2015-08-18T08:58:34.870590+00:00 app[web.6]:   File "/app/.heroku/src/thumbor/thumbor/handlers/__init__.py", line 389, in _fetch
2015-08-18T08:58:34.870592+00:00 app[web.6]:     self.context.request.engine.load(buffer, extension)
2015-08-18T08:58:34.870593+00:00 app[web.6]:   File "/app/.heroku/src/thumbor/thumbor/engines/__init__.py", line 96, in load
2015-08-18T08:58:34.870595+00:00 app[web.6]:     image_or_frames = self.create_image(buffer)
2015-08-18T08:58:34.870596+00:00 app[web.6]:   File "/app/.heroku/src/thumbor/thumbor/engines/pil.py", line 52, in create_image
2015-08-18T08:58:34.870597+00:00 app[web.6]:     img = Image.open(BytesIO(buffer))
2015-08-18T08:58:34.870598+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/PIL/Image.py", line 2266, in open
2015-08-18T08:58:34.870599+00:00 app[web.6]:     im = factory(fp, filename)
2015-08-18T08:58:34.870600+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/PIL/ImageFile.py", line 97, in __init__
2015-08-18T08:58:34.870602+00:00 app[web.6]:     self._open()
2015-08-18T08:58:34.870603+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 502, in _open
2015-08-18T08:58:34.870604+00:00 app[web.6]:     s = self.png.call(cid, pos, length)
2015-08-18T08:58:34.870605+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 132, in call
2015-08-18T08:58:34.870606+00:00 app[web.6]:     return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
2015-08-18T08:58:34.870607+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 302, in chunk_iCCP
2015-08-18T08:58:34.870608+00:00 app[web.6]:     icc_profile = _safe_zlib_decompress(s[i+2:])
2015-08-18T08:58:34.870609+00:00 app[web.6]:   File "/app/.heroku/python/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 85, in _safe_zlib_decompress
2015-08-18T08:58:34.870610+00:00 app[web.6]:     raise ValueError("Decompressed Data Too Large")
2015-08-18T08:58:34.870612+00:00 app[web.6]: ValueError: Decompressed Data Too Large
```

this is our configuration setting:

```
USE_CUSTOM_ERROR_HANDLING = True
ERROR_HANDLER_MODULE = 'thumbor.error_handlers.sentry'
SENTRY_DSN_URL = os.getenv('SENTRY_DSN_URL')
```

since my tornado knowledge is limited, from looking at the code, i could not really understand how this is supposed to work. from the tornado docs it looks like `log_exception` should be called internally?

**Comment by masom** [comment] 2015-08-18 14:02
I think this is a regression introduced with the use of generators in version 5.x.x

It seems like error handling is not hooked up properly with the generators. If the callback is not executed nothing happens and the exception bubbles up to the main loop.

**Comment by heynemann** [comment] 2015-08-18 22:06
We'll try to tackle this but I'm on a trip. As soon as I'm back I'll try to handle this.

**Comment by mkopit** [comment] 2015-08-19 05:44
Ah - I noticed today that feeding thumbor an invalid image file results in an exception in the logs and the http response is never completed (although the connection seems to remain open)

eg.
http://thumbor.thumborize.me/unsafe/http://s3.amazonaws.com/ao-dev-public/invalid.jpg

Do you think this is likely the same issue?

**Comment by heynemann** [comment] 2015-08-19 13:23
I don't think it's the same.

**Comment by phoet** [comment] 2015-08-19 15:39
:clap:

**Comment by heynemann** [comment] 2015-08-20 17:38
Does #541 fix this in its entirety @masom? Can we close this?

**Comment by masom** [comment] 2015-08-20 17:41
@heynemann We'll have to audit the code and make sure context.log_exception is called when an exception is being handled.

#541 solves this exact issue but does not address some errors not showing up in the custom error handlers.

**Comment by heynemann** [comment] 2015-08-20 17:42
I'll take a look at it now! :)

**Comment by heynemann** [comment] 2015-08-25 21:32
I didn't have time to check this yet. Hopefully someone will be able to help.

**Comment by ryanio** [comment] 2015-11-04 03:20
+1, is error logging via sentry still broken? It doesn't seem to be working for me

**Comment by heynemann** [comment] 2015-11-04 12:34
Really? It should be working...

**Comment by phoet** [comment] 2015-11-04 12:40
I think it is working, but we had to disable it because the Raven client
was incompatible with our sentry server. So I can't say for sure...

Bernardo Heynemann <notifications@github.com> schrieb am Mi., 4. Nov. 2015,
13:34:

**Comment by ryanio** [comment] 2015-11-04 20:01
How can I help debug? I have my getsentry.com DSN url in there but have never received any errors

**Comment by dhardy92** [comment] 2015-11-05 14:02
their is other way to get logs to external system using THUMBOR_LOG_CONFIG setting:
my case using custom logguer implementation for Flume (my own implementation of logging.handler)
```
THUMBOR_LOG_CONFIG = {
  'version': 1,
  'disable_existing_loggers': False,
  'handlers': {
    'flumeHandler': {
      'class': 'FlumeHTTPHandler.FlumeHTTPHandler',
      'level': 'WARN',
      'host': 'localhost:9997',
      'url': '/'
    }
  },
  'root': {
    'handlers': ['flumeHandler'],
    'level': 'INFO'
  }
}
```
so you can do the same using : https://raven.readthedocs.org/en/latest/integrations/logging.html
cf #415

**Comment by masom** [comment] 2015-11-05 14:05
@ryanio Thumbor actually does not fail often. It's pretty rare unexpected exceptions are raised.

Most of the errors are due to invalid images or failing upstream servers ( ex: redis or http loader ). Those errors are handled inside thumbor and do not result in an exception being logged into the exception handler.

The metrics system gives a lot more insight for "normal" runtime errors and as @dhardy92 commented the logger can be changed to log elsewhere.

**Comment by ryanio** [comment] 2015-11-08 01:30
@masom Ah that makes sense. Yeah it's really important for me to be alerted when reids fails, so I can jump in and fix. I'll look into implementing @dhardy92's solution. Thanks everyone!

**Closed** 2016-07-01 22:26 UTC

**Comment by kkopachev** [comment] 2016-07-08 22:35
Got the same issue with gifsicle engine and broken (kind of) gif image. ![giphy-15](https://cloud.githubusercontent.com/assets/2279051/16703350/74d48178-4521-11e6-9f47-186e7c9876d5.gif) 
Gif image is truncated, gifsicle failing with 
> read error: missing 88541 pixels of image data
fatal error: too many missing pixels, giving up


Traceback:

```
2016-07-08 20:35:29 thumbor:ERROR [GIF_ENGINE] invalid gif engine result for url `/4A9wg09DfRh91i1LJZhjrO83eb4=/fit-in/160x160/filters:format_auto():strip_icc()/2014/09/26/819/n/1922153/a364d0a91127317f_giphy-15.gif`.
2016-07-08 20:35:41 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 267, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 331, in finish_request
    callback=inner,
  File "/usr/local/lib/python2.7/site-packages/thumbor/context.py", line 268, in queue
    self._execute_in_foreground(operation, callback)
  File "/usr/local/lib/python2.7/site-packages/thumbor/context.py", line 255, in _execute_in_foreground
    result.set_result(operation())
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 267, in _load_results
    results = context.request.engine.read(image_extension, quality)
  File "/usr/local/lib/python2.7/site-packages/thumbor/engines/gif.py", line 107, in read
    with Image.open(BytesIO(self.buffer)) as image:
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file <_io.BytesIO object at 0x7ff804a23590>
```

From what I can see there is no exception catching in ThreadPool. I am not big python guru, so I have no idea what would be proper fix for that. I was thinking about something like this:

```diff
diff --git a/thumbor/context.py b/thumbor/context.py
index 88fa083..270108d 100644
--- a/thumbor/context.py
+++ b/thumbor/context.py
@@ -260,7 +260,11 @@ class ThreadPool(object):
 
     def _execute_in_foreground(self, operation, callback):
         result = Future()
-        result.set_result(operation())
+        try:
+            result.set_result(operation())
+        except Exception as e:
+            result.set_exception(e)
+
         callback(result)
 
     def _execute_in_pool(self, operation, callback):
```

```diff
diff --git a/thumbor/handlers/__init__.py b/thumbor/handlers/__init__.py
index aa4de24..d0a2759 100644
--- a/thumbor/handlers/__init__.py
+++ b/thumbor/handlers/__init__.py
@@ -320,6 +320,19 @@ class BaseHandler(tornado.web.RequestHandler):
             context.config.RESULT_STORAGE_STORES_UNSAFE or not context.request.unsafe)
 
         def inner(future):
+            """
+            :type future: Future
+            """
+            exception = future.exception()
+            if exception:
+                msg = '[BaseHandler] get_image failed for url `{url}`. error: `{error}`'.format(
+                    url = self.context.request.image_url,
+                    error = exception
+                )
+                logger.error(msg)
+                self._error(500)
+                return
+
             results, content_type = future.result()
             self._write_results_to_client(context, results, content_type)
```

**Comment by kkopachev** [comment] 2016-07-08 22:36
Similar traceback (_execute_in_foreground) I am getting on some images where PIL engine is calling `paste` method.

**Comment by NovaDev94** [comment] 2017-01-10 11:25
The same problem is raised when we have an exception raised in custom filters. The exception was logged:

```
2017-01-10 18:17:21 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
```

But seems like the error handler isn't called.  

It's dirty to have something like this and manually hook it everywhere it can raise an exception...

```python
def report_error(context):
    import sys
    return context.request_handler.log_exception(*sys.exc_info())

try:
    # do something here
except:
    report_error(self.context)
```
