### ISSUE TITLE
Some transparent PNGs have black inserted as the background colour

### ISSUE THREAD

**Issue by onassar** [thumbor/thumbor#987] opened 2017-09-22 21:27 UTC
### Thumbor request URL

Broken:
Original: https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld6878b91f
Resized: https://d32q3izcmhqbti.cloudfront.net/174x0/upld6878b91f

Working:
Original: https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld65b35218
Resized: https://d32q3izcmhqbti.cloudfront.net/174x0/upld65b35218

### Expected behaviour
Any transparent PNGs that are resized should have their backgrounds kept as transparent.

### Actual behaviour
Some are having black pixels inserted in place of transparent pixels.

### Operating system
OSx / Chrome

### Your thumbor.conf
Using through an AWS template, so don't have the config file handy.

**Comment by kkopachev** [comment] 2017-09-23 00:30
same as https://github.com/thumbor/thumbor/issues/945 and https://github.com/thumbor/thumbor/issues/943
and going to be fixed in next pillow release (Oct 1) https://github.com/python-pillow/Pillow/issues/2702

or someone can put some lines into as a workaround around here https://github.com/thumbor/thumbor/commit/f945871a3673b1be9340ef9c1e3ac78d9f9fd359#diff-4766ae01206209cf72a83c6784669e00R134

**Comment by onassar** [comment] 2017-09-23 17:12
The codebase I have already has that code in it:
![](https://i.imgur.com/667jzbC.png)

**Comment by onassar** [comment] 2017-09-23 19:37
Ahh I see what you're saying. These lines are the problem, and need to be updated, yes?

**Comment by kkopachev** [comment] 2017-09-24 08:18
looks like it's something different then.

**Comment by kkopachev** [comment] 2017-09-24 09:00
the issue is from here https://github.com/thumbor/thumbor/pull/227/files#diff-4766ae01206209cf72a83c6784669e00R131 It become an issue since resize method now converts P image to RGBA for better conversion and then back. It used to keep image as RGBA after resize, so this code didn't affect it.

**Comment by onassar** [comment] 2017-09-25 02:03
Hmm okay; any recommendations?
I've tested it with your official http://thumbor.thumborize.me/ server, and the same issue is visible there.

**Comment by onassar** [comment] 2017-09-25 18:09
Here's a follow up on examples that do not work:

Source:  https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld714476a0
Resized: http://thumbor.thumborize.me/unsafe/fit-in/200x200/filters:format(png)/https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld714476a0

Source:  https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld6878b91f
Resized: http://thumbor.thumborize.me/unsafe/fit-in/200x200/filters:format(png)/https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld6878b91f

Source:  http://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld65bea346
Fails:   http://thumbor.thumborize.me/unsafe/fit-in/200x200/filters:format(png)/http://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld65bea346 (times out)

Source:  http://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upldf944c476
Resized: http://thumbor.thumborize.me/unsafe/fit-in/200x200/filters:format(png)/http://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upldf944c476

**Comment by kkopachev** [comment] 2017-09-25 18:32
Pillow version which fixes last issue isn't released yet and will be on October 1st. 
I added workaround and fix for other 2 examples https://github.com/thumbor/thumbor/pull/988
I'm not maintainer of thumbor, so can't merge. Please thumbsup on PR.

**Comment by onassar** [comment] 2017-09-25 20:48
Will this work around conflict with Pillow? I tested the Pillow fix yday, and it didn't seem to fix all the issues.

**Comment by onassar** [comment] 2017-10-07 15:24
Was this merged in on Oct 1?
Would be happy to test it

**Comment by kkopachev** [comment] 2017-10-09 19:25
pillow release will only fix [another transparent png issue](https://github.com/thumbor/thumbor/issues/943)

**Comment by krazyjakee** [comment] 2017-11-07 10:41
What's the status with this?

**Comment by onassar** [comment] 2017-11-14 17:39
Possible that maybe this could address some of the short-comings?
https://github.com/uploadcare/pillow-simd

**Comment by robinbowes** [comment] 2017-11-23 11:24
I'd appreciate an update on the status of this issue, too.

It seems to me that pillow has been fixed, and @kkopachev has some fixed for thumbor. Do we just need to bump thumbor to use a later version of pillow, merge @kkopachev's fixes, and cut a new release?

**Comment by heynemann** [comment] 2017-11-23 13:07
I'm currently working in an improved version of thumbor, but I will try to catch up with Pull Requests starting tonight. Sorry for that. Since this has already been merged, it'll be released once I can catch up and ensure that we can release a stable version.

**Comment by onassar** [comment] 2017-11-23 13:09
Thanks @heynemann 
I'm eagerly awaiting the update :-D

**Comment by robinbowes** [comment] 2017-11-23 14:10
@heynemann I'm not sure that it has actually been merged - it's merged into @kkopachev's repo, but I don't think it's been merged to this one? Isn't it #988 ?

**Closed** 2017-11-29 13:02 UTC
