### ISSUE TITLE
Make gifsicle configurable in ENV vars?

### ISSUE THREAD

**Issue by lephyrius** [thumbor/thumbor#1005] opened 2017-11-06 12:06 UTC
Is it possible to make gifsicle configurable in environment variables?

**Comment by krazyjakee** [comment] 2017-11-07 09:49
Speaking on behalf of OP.

Specifically the path of the binary. The problem is that gifsicle is compiled into a custom location as we have to ship it with the lambda package. It's not in the PATH so thumbor can't find it.

**Comment by heynemann** [comment] 2017-11-16 00:50
I'm all for allowing configurations (thumbor even spawned derpconf as a baby project), but I'm very keen on reducing thumbor feature set. The codebase is hard to maintain as is. Isn't this as simple as running thumbor with `PATH=/path/to/gifsicle:$PATH thumbor`, if you can't set the path any other way?

For now I'm closing this. If more people think this is a good idea, we can move forward with a PR.

If you have any further questions on this subject, please reopen this issue.

**Closed by heynemann** 2017-11-16 00:50 UTC
