### ISSUE TITLE
Support for LSR format

### ISSUE THREAD

**Issue by Bladrak** [thumbor/thumbor#829] opened 2016-11-14 10:16 UTC
# Feature Request

LSR format is an image format issued by Apple, mainly in use in iOS and tvOS, that allows a parallax effect to be displayed. It is documented here: https://developer.apple.com/library/content/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/LSRFormatOverview.html#//apple_ref/doc/uid/TP40015170-CH44-SW1

Thumbor should be able to process images in LSR format, resize them, and return them, as it does with other images, given it's simply a combination of several images.

What do you think about it?

**Comment by Arthien** [comment] 2016-11-18 14:35
I believe the only issue with this feature would be image type filters applied. Going from LSR to say PNG wouldn't be a problem. The issue is when we filter a non LSR file as LSR. This feature would probably be limited in the scope of thumbor's service as it's conversion is only one way.

I do however agree that it would be a great feature to support it as a base functionality for resizing.

**Comment by Bladrak** [comment] 2017-10-30 16:04
For going to non-LSR to LSR, we might be able to superpose a transparent image, so it wouldn't change in any way.

**Comment by heynemann** [comment] 2017-11-16 01:48
Unless Pillow supports it, we won't include it in Thumbor. When we wanted to support WebP, the team contributed to Pillow support for WebP. Do you think that's something you might be able to do?

For now I'm closing this.
If you have any further questions on this issue, please reopen it.

**Closed by heynemann** 2017-11-16 01:48 UTC
