### ISSUE TITLE
using trim with certain transparent png's results in not-transparent images

### ISSUE THREAD

**Issue by LeonB** [thumbor/thumbor#520] opened 2015-07-29 15:43 UTC
Original:
![pallas_m_fix_moondust original](https://cloud.githubusercontent.com/assets/3979/8961890/11529f72-3618-11e5-8187-0b8ffdce4139.png)

With trim (wrong / no transparency):
![pallas_m_fix_moondust 1](https://cloud.githubusercontent.com/assets/3979/8961891/115de01c-3618-11e5-9253-eec65800983a.png)

Without trim (transparency = good):
![pallas_m_fix_moondust](https://cloud.githubusercontent.com/assets/3979/8961892/1167046c-3618-11e5-8b8c-ba21753bdf15.png)

I had the idea maybe this could be the problem: https://github.com/thumbor/thumbor/blob/master/thumbor/transformer.py#L96

**Comment by LeonB** [comment] 2015-07-29 16:01
Yeah, when returning before image_data_as_rgb() the transparency is reserverd. Returning directly after that call converts the transparency to black.

**Comment by LeonB** [comment] 2015-07-29 20:43
This works for me:

``` diff
--- a/thumbor/transformer.py
+++ b/thumbor/transformer.py
@@ -93,7 +93,7 @@ class Transformer(object):
         if self.context.request.trim is None or not trim_enabled or is_gifsicle:
             return
 
-        mode, data = self.engine.image_data_as_rgb()
+        mode, data = self.engine.image_data_as_rgb(Update=False)
         box = _bounding_box.apply(
             mode,
             self.engine.size[0],
```

I'm installing the test environment to run `make ci_test` and see if anything broke.

**Comment by guilhermef** [comment] 2015-07-29 21:04
Palleted PNG mode is represented by a P, https://github.com/thumbor/thumbor/blob/master/thumbor/engines/pil.py#L226
Since we ignore it, we just convert the image to RGB instead of RGBA

**Comment by LeonB** [comment] 2015-07-29 21:18
@guilhermef thanks! Would something like this work?

``` diff
--- a/thumbor/engines/pil.py
+++ b/thumbor/engines/pil.py
@@ -225,6 +225,8 @@ class Engine(BaseEngine):
         if converted_image.mode not in ['RGB', 'RGBA']:
             if 'A' in converted_image.mode:
                 converted_image = converted_image.convert('RGBA')
+            if 'P' in converted_image.mode:
+                converted_image = converted_image.convert('RGBA')
             else:
                 converted_image = converted_image.convert('RGB')
         if update_image:
```

**Comment by guilhermef** [comment] 2015-07-29 21:19
I'm still testing to see what will happen

**Comment by LeonB** [comment] 2015-07-29 21:23
Ok, thanks. Is het first diff also something that could be accepted as a change? It seems to me image_data_as_rgb() on that line is only used to determine what the bounding box is. So changing the original image is a bit of a side-effect? Or am I wrong in that?

**Comment by guilhermef** [comment] 2015-07-29 21:39
We use this to give a normalized buffer to other engines or filters,
the problem is that we assume that a pallete mode doesn't have an Alpha channel.
I'll push a change to keep Pallete mode, but I'm still trying to validate if something will break.

**Comment by guilhermef** [comment] 2015-07-29 21:41
That should solve: https://github.com/thumbor/thumbor/commit/e719195f172fe24f3ecb124fae002b5a6230755f
Do you mind testing ?

**Comment by LeonB** [comment] 2015-07-29 21:49
The image renders correctly with transparency now. Also the `make redis mongo ci_test` reported 
```
  ✓ OK » 980 honored • 0 broken (8.534986s)
```

**Comment by guilhermef** [comment] 2015-07-29 21:56
The tests are passing but I'm afraid that this could mess up some images colors,
I'll run more tests during the week.

**Comment by LeonB** [comment] 2015-07-29 21:57
Understandable. I've updated my live environment to e719195f17 to see if anything breaks.

**Comment by guilhermef** [comment] 2015-07-29 21:58
Thanks @LeonB, let me know if something happens.
I'll keep this issue open while we test.

**Comment by LeonB** [comment] 2015-07-29 22:01
Thank you! I'll keep monitoring it for a week or so on the webshop I'm using it on. Using thumbor cut down the pagesize of the homepage from 3.5mb to 1.0mb. Thumbor is an awesome project!

**Comment by guilhermef** [comment] 2015-07-29 22:23
Have you enabled auto_webp ?

**Comment by LeonB** [comment] 2015-07-30 08:15
Yeah, auto_webp is on.

**Comment by guilhermef** [comment] 2015-07-31 14:05
@LeonB How's Thumbor treating you ? everything ok ?

**Comment by LeonB** [comment] 2015-07-31 16:08
Yeah, everything is great so far. I've got 4 thumbor processes running behind nginx on a server that's already doing stuff and the load of thumbor isn't really noticeable. Only thing is when loading a page with lots of (resized) images it takes a while to load them all. So maybe I have to bump up the number of processes.

Setting thumbor up was fairly easy. Only thing I had a little trouble with was getting remotecv + webp to work at the same time. Maybe I'll write a blog post on how my setup is.

**Comment by guilhermef** [comment] 2015-07-31 17:30
Are you using a result_storage ?

**Comment by LeonB** [comment] 2015-07-31 19:37
No, I don't believe so.

If the original image changes will thumbor pick up on the changes? Is there some kind of setting for that?

**Comment by guilhermef** [comment] 2015-07-31 19:42
You can set an expiration, that will cause Thumbor to reload the image: https://github.com/thumbor/thumbor/blob/master/thumbor/config.py#L162

But you should set a RESULT_STORAGE: https://github.com/thumbor/thumbor/blob/master/thumbor/config.py#L89
that will cache the crop result and use it on other requests instead of cropping again.

**Comment by LeonB** [comment] 2015-07-31 19:47
Can all the storages be set to `thumbor.storages.redis_storage`? That isn't entirely clear from the documentation.

**Comment by guilhermef** [comment] 2015-07-31 19:50
No, Thumbor has two kinds ot storage, the thumbor.storage, is responsible for caching the image that you got from the external server or filer, a.k.a the original image, and there's the thumbor.result_storage, that caches the image generated by Thumbor.

**Comment by LeonB** [comment] 2015-07-31 19:55
Ah, ok. And the other storages (MIXED_STORAGE_FILE_STORAGE, MIXED_STORAGE_CRYPTO_STORAGE & MIXED_STORAGE_DETECTOR_STORAGE) can use the 'thumbor.storages.redis_storage'.

I'll create some cronjob or something to clean up /tmp/thumbor/result_storage/ every few weeks or so.

**Comment by guilhermef** [comment] 2015-07-31 19:56
You don't need a cronjob, result_storage has expiration too.

**Comment by guilhermef** [comment] 2015-07-31 20:04
There's a wiki for that https://github.com/thumbor/thumbor/wiki/Image-storage

**Comment by LeonB** [comment] 2015-07-31 20:06
Ah, nice. So setting RESULT_STORAGE_EXPIRATION_SECONDS to a month will also remove stale / old files from disk?

**Comment by guilhermef** [comment] 2015-08-03 12:55
No @LeonB, It won't remove from the disk.

**Comment by masom** [comment] 2015-08-05 14:25
@LeonB we use redis_storage and a redis_result_storage with a 16gb database and it's great. Check it out at https://popkey.co

**Comment by LeonB** [comment] 2015-08-10 07:20
@masom with a custom redis result_storage adapter?

**Comment by masom** [comment] 2015-08-10 14:01
Yep. We might open source it but it's pretty much of a copy of `redis_storage` that implements the methods for `result_storage`.

**Comment by LeonB** [comment] 2015-08-11 13:07
@masom would be nice!

**Comment by heynemann** [comment] 2015-08-18 22:10
Yay @masom for creating the redis project in thumbor community :)

**Comment by LeonB** [comment] 2015-08-20 08:35
No issues so far. Has worked flawlessly for the last three weeks!

**Comment by heynemann** [comment] 2015-08-20 13:01
Good to hear @LeonB . sorry for the issues.

**Comment by heynemann** [comment] 2015-09-08 21:25
Closing this as it appears to be fixed.

**Closed by heynemann** 2015-09-08 21:25 UTC
