### ISSUE TITLE
Malformed URL with ~

### ISSUE THREAD

**Issue by sradu** [thumbor/thumbor#814] opened 2016-09-30 05:08 UTC
### Thumbor request URL

http://demandware.edgesuite.net/sits_pod26/dw/image/v2/AAGU_PRD/on/demandware.static/-/Sites-giggle-master/default/dw757c68bc/images/large/LG_MS21910~NB.jpg?sw=542&sh=542
### Expected behaviour

It should load the image. Other images work, so it's not the security key.
### Actual behaviour

It returns Malformed request.
### Operating system

Ubuntu
### Using this NodeJS code:

var urlToSign = escape(imageURL);

var sig = crypto.createHmac('sha1', config.thumborSecurityKey).update(urlToSign).digest('base64');

sig = sig.replace(/+/g, '-').replace(/\//g, '_');

**Comment by Arthien** [comment] 2016-09-30 19:41
That is because of the query string you have append `?sw=542&sh=542`. Check out #813 for more details.

**Comment by sradu** [comment] 2016-09-30 20:30
I believe it's related to the tilda. A lot of other URL arguments work perfectly, and there were some previous tickets about it, with some changes that are not in master anymore..

**Comment by masom** [comment] 2016-12-12 15:44
@sradu Are you urlencoding your image path?

The query string itself will be used by thumbor and will not be passed upstream as per the HTTP specification.

If you want thumbor to forward query parameters, the entire image source URL should be urlencoded.

**Comment by sradu** [comment] 2016-12-12 18:51
@mason yes, the image URL is encoded.

`var urlToSign = escape(imageURL);`

**Comment by aoqfonseca** [comment] 2017-01-05 16:37
I have the same problem here.

**Comment by mpilar** [comment] 2017-02-23 21:36
@sradu @aoqfonseca what @masom means is that you might not be urlencoding the URL you are requesting to thumbor, can you paste the thumbor URL? Not just the image you're sending to thumbor but the thumbor URL itself with the image (you can obfuscate the signature).

**Comment by renanborgez** [comment] 2017-03-06 13:42
@sradu The problem is you are encrypting the querystring

```?sw=542&sh=542```

Try remove it before encrypt your url 

Look what i done in my code...
```
const crypto = require('crypto-js');
const url = require('url');


module.exports = function (urlPath) {
  let urlObj = url.parse(urlPath, false);
  let key = crypto.HmacSHA1(urlObj.href.replace(urlObj.search, ''), globalVariables.THUMBOR_SECURITY_KEY);
  key = crypto.enc.Base64.stringify(key);

  key = key.replace(/\+/g, '-').replace(/\//g, '_');
  return globalVariables.THUMBOR_URL + '/' + key + '/' + urlPath;
};
```

**Comment by heynemann** [comment] 2017-11-16 01:50
Closing this issue.

If you have any further questions on this issue, please reopen it.

**Closed by heynemann** 2017-11-16 01:50 UTC
